default: &default
  adapter: postgresql
  host: 172.17.0.2
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: hr-til_development

test: &test
  <<: *default
  database: hr-til_test

cucumber:
  <<: *test

staging:
  <<: *default
  database: hr-til_development

production:
  <<: *default
  database: hr-til_development
